version: '3'

services:
  gitbook:
    build:
      args:
        - VERSION
      context: ./gitbook
      dockerfile: Dockerfile
    container_name: knowledge_backend
    restart: always
    working_dir: /srv/gitbook
    networks:
      - appnet

  webserver:
    image: nginx:alpine
    container_name: knowledge_proxy_server
    restart: always
    tty: true
    volumes:
      - ./configs/nginx:/etc/nginx/conf.d
    ports:
      - 4100:80
      - 4106:443
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
